  # -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :zoo do |zoo|
    zoo.vm.hostname = "zk1"
    zoo.vm.box = "bento/centos-7.3"
    zoo.vm.network :private_network, ip: "192.168.21.81"
  end

  config.vm.define :solr1 do |solr1|
    solr1.vm.hostname = "solr1"
    solr1.vm.box = "bento/centos-7.3"
    solr1.vm.network :private_network, ip: "192.168.21.82"
  end

  config.vm.define :solr2 do |solr2|
    solr2.vm.hostname = "solr2"
    solr2.vm.box = "bento/centos-7.3"
    solr2.vm.network :private_network, ip: "192.168.21.83"
  end

  config.vm.define :solr3 do |solr3|
    solr3.vm.hostname = "solr3"
    solr3.vm.box = "bento/centos-7.3"
    solr3.vm.network :private_network, ip: "192.168.21.84"
  end


end
