  # -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.define :httpd do |httpd|
    httpd.vm.hostname = "ammacomm"
    httpd.vm.network :forwarded_port, guest: 80, host: 4567
    httpd.vm.network :private_network, ip: "192.168.50.4"
    httpd.vm.provision :shell, path: "bootstrap.sh"
  end

end
